// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aukavbitkvycfsducudn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1a2F2Yml0a3Z5Y2ZzZHVjdWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjAwODAsImV4cCI6MjA2MjA5NjA4MH0.E9lATNveqvmthFYasHkWgkWBvYsnhOF2TgFD6ZP0dCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);